E-RIMS/Models/AcademicPaper.cs
using E_RIMS.FileValidation;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_RIMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class AcademicPaper
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string name { get; set; }
        public string @abstract { get; set; }
        public string category { get; set; }
        public string creator { get; set; }
        public string files { get; set; }
        [FileExtensionsValidationDoc]
        public HttpPostedFileBase files2 { get; set; }
    }
}

E-RIMS/Controllers/AcademicPaperController.cs
using E_RIMS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.IO;
using PagedList;
using PagedList.Mvc;

namespace E_RIMS.Controllers
{
    public class AcademicPaperController : Controller
    {
        ERIMSEntities db = new ERIMSEntities();
        // GET: AcademicPaper
        public ActionResult Index(string search,int? page)
        {
            var academicPaper = db.AcademicPaper;

            //--Pagination 10 each
            var academicPaperResult = academicPaper.ToList().ToPagedList(page ?? 1, 10);
            
            //--Search Engine
            if (search != null)
            {
                if (search != null)
                {
                    academicPaperResult = db.AcademicPaper.Where(x => x.name.StartsWith(search) || x.name == search).ToList().ToPagedList(page ?? 1, 10);             
                }
                else if (search != null)
                {
                    academicPaperResult = db.AcademicPaper.Where(x => x.@abstract.StartsWith(search) || x.@abstract == search).ToList().ToPagedList(page ?? 1, 10);
                }
                else if (search != null)
                {
                    academicPaperResult = db.AcademicPaper.Where(x => x.creator.StartsWith(search) || x.creator == search).ToList().ToPagedList(page ?? 1, 10);
                }
            }
            //--

                return View(academicPaperResult);
        }

        public ActionResult AllAcademicPaper()
        {
            var academicPaper = db.AcademicPaper;
            return View(academicPaper.ToList());
        }

        public ActionResult CreateAcademicPaper()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateAcademicPaper(AcademicPaper academicPaper)
        {
            if (ModelState.IsValid)
            {
                if (academicPaper.files2 != null)
                {
                    var fileNameDoc = Path.GetFileNameWithoutExtension(academicPaper.files2.FileName);
                    string extension = Path.GetExtension(academicPaper.files2.FileName);
                    fileNameDoc = fileNameDoc + "_" + DateTime.Now.ToString("ddMMyy_HHmmss") + extension;
                    academicPaper.files = "/docUploadAcademicPaper/" + fileNameDoc;
                    var path = Path.Combine(Server.MapPath("~/docUploadAcademicPaper/"), fileNameDoc);
                    academicPaper.files2.SaveAs(path);
                }

                db.AcademicPaper.Add(academicPaper);
                db.SaveChanges();
                ModelState.Clear();

                return RedirectToAction("Index");
            }
            return View(academicPaper);
        }


        public ActionResult DetailAcademicPaper(int id)
        {
            AcademicPaper academicPaper = db.AcademicPaper.Find(id);
            if (academicPaper == null)
            {
                return RedirectToAction("Index");
            }
            return View(academicPaper);
        }

        public ActionResult EditAcademicPaper(int id)
        {
            AcademicPaper academicPaper = db.AcademicPaper.Find(id);
            if (academicPaper == null)
            {
                return RedirectToAction("Index");
            }
            return View(academicPaper);
        }

        [HttpPost]
        public ActionResult EditAcademicPaper(AcademicPaper academicPaper)
        {
            if (ModelState.IsValid)
            {
                if (academicPaper.files2 != null)
                {
                    var fileNameDoc = Path.GetFileNameWithoutExtension(academicPaper.files2.FileName);
                    string extension = Path.GetExtension(academicPaper.files2.FileName);
                    fileNameDoc = fileNameDoc + "_" + DateTime.Now.ToString("ddMMyy_HHmmss") + extension;
                    academicPaper.files = "/docUploadAcademicPaper/" + fileNameDoc;
                    var path = Path.Combine(Server.MapPath("~/docUploadAcademicPaper/"), fileNameDoc);
                    academicPaper.files2.SaveAs(path);
                }

                db.Entry(academicPaper).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(academicPaper);
        }

        public ActionResult DeleteAcademicPaper(int id)
        {
            AcademicPaper academicPaper = db.AcademicPaper.Find(id);
            if (academicPaper == null)
            {
                return RedirectToAction("Index");
            }
            return View(academicPaper);
        }

        [HttpPost,ActionName("DeleteAcademicPaper")]
        public ActionResult DeleteAcademicPaperConfirm(int id)
        {
            AcademicPaper academicPaper = db.AcademicPaper.Find(id);
            db.AcademicPaper.Remove(academicPaper);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

E-RIMS/Views/AcademicPaper/AllAcademicPaper.cshtml
@{
    ViewBag.Title = "AllAcademicPaper";
}

<br><br>
<h3><strong>ผลงานวิชาการ</strong></h3>
<a href="@Url.Action("CreateAcademicPaper","AcademicPaper")"><h6 class="text-primary">+เพิ่มผลงานวิชาการ</h6></a>

<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">ที่</th>
            <th scope="col">ชื่อเรื่อง</th>
            <th scope="col">บทคัดย่อ</th>
            <th scope="col">ประเภท</th>
            <th scope="col">ผู้จัดทำ</th>
            <th scope="col">เอกสาร</th>
            <th scope="col">การกระทำ</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">1</th>
            <td>......</td>
            <td>.....</td>
            <td>.....</td>
            <td>.....</td>
            <td><img src="~/Image/download-solid.svg" width="20" height="20"></td>
            <td><img src="~/Image/pencil-alt-solid.svg" width="20" height="20">&nbsp;<img src="~/Image/trash-alt-regular.svg" width="20" height="20"></td>

        </tr>
        <tr>
            <th scope="row">2</th>
            <td>.....</td>
            <td>.....</td>
            <td>.....</td>
            <td>.....</td>
            <td><img src="~/Image/download-solid.svg" width="20" height="20"></td>
            <td><img src="~/Image/pencil-alt-solid.svg" width="20" height="20">&nbsp;<img src="~/Image/trash-alt-regular.svg" width="20" height="20"></td>


        </tr>
        <tr>
            <th scope="row">3</th>
            <td>.....</td>
            <td>.....</td>
            <td>.....</td>
            <td>.....</td>
            <td><img src="~/Image/download-solid.svg" width="20" height="20"></td>
            <td><img src="~/Image/pencil-alt-solid.svg" width="20" height="20">&nbsp;<img src="~/Image/trash-alt-regular.svg" width="20" height="20"></td>

        </tr>
        <tr>
            <th scope="row">4</th>
            <td>.....</td>
            <td>.....</td>
            <td>.....</td>
            <td>.....</td>
            <td><img src="~/Image/download-solid.svg" width="20" height="20"></td>
            <td><img src="~/Image/pencil-alt-solid.svg" width="20" height="20">&nbsp;<img src="~/Image/trash-alt-regular.svg" width="20" height="20"></td>

        </tr>
        <tr>
            <th scope="row">5</th>
            <td>.....</td>
            <td>.....</td>
            <td>.....</td>
            <td>.....</td>
            <td><img src="~/Image/download-solid.svg" width="20" height="20"></td>
            <td><img src="~/Image/pencil-alt-solid.svg" width="20" height="20">&nbsp;<img src="~/Image/trash-alt-regular.svg" width="20" height="20"></td>

        </tr>
    </tbody>
</table>

<div>
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-end">
            <li class="page-item"><a class="page-link" href="#">Previous</a></li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item"><a class="page-link" href="#">2</a></li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item"><a class="page-link" href="#">Next</a></li>
        </ul>
    </nav>
</div>

E-RIMS/Views/AcademicPaper/CreateAcademicPaper.cshtml
@{
    ViewBag.Title = "CreateAcademicPaper";
}

<br/><br/>
<h3><strong>เพิ่มผลงานวิชาการ</strong></h3>
<hr>
<form class="form-inline">
    <label class="mr-sm-2">ชื่อเรื่อง</label>
    <input type="text" class="form-control mb-2 mr-sm-2">
    <label class="mr-sm-2">บทคัดย่อ</label>
    <input type="text" class="form-control mb-2 mr-sm-2">
    <label class="mr-sm-2">ประเภท</label>
    <select class="form-control mb-2 mr-sm-2">
        <option>...</option>
        <option>.....</option>
    </select>
    <label class="mr-sm-2">ผู้จัดทำ</label>
    <input type="text" class="form-control mb-2 mr-sm-2">
    <label class="mr-sm-2">ไฟล์/วิดีโอ</label>
    <input type="file" class="form-control-file">
</form>
<div class="row justify-content-center">
    <button type="submit" class="btn btn-outline-success text-center">บันทึก</button>
</div>

E-RIMS/Views/AcademicPaper/DeleteAcademicPaper.cshtml
@model E_RIMS.Models.AcademicPaper

@{
    ViewBag.Title = "DeleteAcademicPaper";
}

<h2>DeleteAcademicPaper</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AcademicPaper</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.abstract)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.abstract)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.category)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.creator)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.creator)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.files)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.files)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

E-RIMS/Views/AcademicPaper/DetailAcademicPaper.cshtml
@model E_RIMS.Models.AcademicPaper

@{
    ViewBag.Title = "DetailAcademicPaper";
}

<h2>DetailAcademicPaper</h2>

<div>
    <h4>AcademicPaper</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.abstract)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.abstract)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.category)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.creator)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.creator)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.files)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.files)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

E-RIMS/Views/AcademicPaper/EditAcademicPaper.cshtml
@model E_RIMS.Models.AcademicPaper

@{
    ViewBag.Title = "EditAcademicPaper";
}

<h2>EditAcademicPaper</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>AcademicPaper</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.abstract, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.abstract, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.abstract, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.category, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.category, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.category, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.creator, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.creator, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.creator, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.files, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.files, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.files, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

E-RIMS/Views/AcademicPaper/Index.cshtml
@{
    ViewBag.Title = "Index";
}