E-RIMS/Controllers/TreasuryWorkController.cs
using E_RIMS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.IO;
using PagedList;
using PagedList.Mvc;

namespace E_RIMS.Controllers
{
    public class TreasuryWorkController : Controller
    {
        ERIMSEntities db = new ERIMSEntities();
        // GET: TreasuryWork
        public ActionResult Index()
        {
            return View();
        }

        // GET: TreasuryWork
        public ActionResult ResearchTreasuryWork(int? page)
        {
            var research = db.Research;

            //--Pagination 10 each Select by Condition.
            var researchResult = research.Where(x => x.type.Equals("วิจัย") && x.workOverview == 100.00M && (x.fileFinishStatusActivity1 != null
            || x.fileFinishStatusActivity2 != null
            || x.fileFinishStatusActivity3 != null
            || x.fileFinishStatusActivity4 != null
            || x.fileFinishStatusActivity5 != null
            || x.fileFinishStatusActivity6 != null
            || x.fileFinishStatusActivity7 != null
            || x.fileFinishStatusActivity8 != null
            || x.fileFinishStatusActivity9 != null
            || x.fileFinishStatusActivity10 != null) && (x.finalFiles != null) && (x.agreePublish == true)).ToList().ToPagedList(page ?? 1, 10);

            if (researchResult.TotalItemCount == 0)
            {
                ViewBag.Nodata = "ไม่พบงานวิจัยที่เสร็จสิ้น";
            }

            return View(researchResult);

        }

        [HttpPost]
        public ActionResult ResearchTreasuryWork(string budgetYear, string name, string creator, string workGroup, int? page)
        {
            var research = db.Research;

            //--Pagination 10 each Select by Condition.
            var researchResult = research.Where(x => x.type.Equals("วิจัย") && x.workOverview == 100.00M && (x.fileFinishStatusActivity1 != null
            || x.fileFinishStatusActivity2 != null
            || x.fileFinishStatusActivity3 != null
            || x.fileFinishStatusActivity4 != null
            || x.fileFinishStatusActivity5 != null
            || x.fileFinishStatusActivity6 != null
            || x.fileFinishStatusActivity7 != null
            || x.fileFinishStatusActivity8 != null
            || x.fileFinishStatusActivity9 != null
            || x.fileFinishStatusActivity10 != null) && (x.finalFiles != null) && (x.agreePublish == true)).ToList().ToPagedList(page ?? 1, 10);

            //--Search Engine
            if (budgetYear != "-- ปีงบประมาณ --")
            {
                researchResult = db.Research.Where(x => x.type.Equals("วิจัย") && x.workOverview == 100.00M && (x.fileFinishStatusActivity1 != null
            || x.fileFinishStatusActivity2 != null
            || x.fileFinishStatusActivity3 != null
            || x.fileFinishStatusActivity4 != null
            || x.fileFinishStatusActivity5 != null
            || x.fileFinishStatusActivity6 != null
            || x.fileFinishStatusActivity7 != null
            || x.fileFinishStatusActivity8 != null
            || x.fileFinishStatusActivity9 != null
            || x.fileFinishStatusActivity10 != null) && (x.finalFiles != null) && (x.budgetYear.StartsWith(budgetYear) || x.budgetYear.Equals(budgetYear)) && (x.agreePublish == true)
            ).ToList().ToPagedList(page ?? 1, 10);

                if (researchResult.TotalItemCount == 0)
                {
                    ViewBag.Nodata = "ไม่พบงานวิจัย";
                }

                return View(researchResult);
            }
            if (name != "")
            {
                researchResult = db.Research.Where(x => x.type.Equals("วิจัย") && x.workOverview == 100.00M && (x.fileFinishStatusActivity1 != null
            || x.fileFinishStatusActivity2 != null
            || x.fileFinishStatusActivity3 != null
            || x.fileFinishStatusActivity4 != null
            || x.fileFinishStatusActivity5 != null
            || x.fileFinishStatusActivity6 != null
            || x.fileFinishStatusActivity7 != null
            || x.fileFinishStatusActivity8 != null
            || x.fileFinishStatusActivity9 != null
            || x.fileFinishStatusActivity10 != null) && (x.finalFiles != null) && (x.name.StartsWith(name) || x.name.Equals(name) || x.name.Contains(name))
            && (x.agreePublish == true)
            ).ToList().ToPagedList(page ?? 1, 10);

                if (researchResult.TotalItemCount == 0)
                {
                    ViewBag.Nodata = "ไม่พบงานวิจัย";
                }

                return View(researchResult);
            }
            if (creator != "")
            {
                researchResult = db.Research.Where(x => x.type.Equals("วิจัย") && x.workOverview == 100.00M && (x.fileFinishStatusActivity1 != null
            || x.fileFinishStatusActivity2 != null
            || x.fileFinishStatusActivity3 != null
            || x.fileFinishStatusActivity4 != null
            || x.fileFinishStatusActivity5 != null
            || x.fileFinishStatusActivity6 != null
            || x.fileFinishStatusActivity7 != null
            || x.fileFinishStatusActivity8 != null
            || x.fileFinishStatusActivity9 != null
            || x.fileFinishStatusActivity10 != null) && (x.finalFiles != null) && (x.creator.StartsWith(creator) || x.creator.Equals(creator) || x.creator.Contains(creator))
            && (x.agreePublish == true)).ToList().ToPagedList(page ?? 1, 10);

                if (researchResult.TotalItemCount == 0)
                {
                    ViewBag.Nodata = "ไม่พบงานวิจัย";
                }

                return View(researchResult);
            }
            if (workGroup != "-- กลุ่มงาน --")
            {
                researchResult = db.Research.Where(x => x.type.Equals("วิจัย") && x.workOverview == 100.00M && (x.fileFinishStatusActivity1 != null
            || x.fileFinishStatusActivity2 != null
            || x.fileFinishStatusActivity3 != null
            || x.fileFinishStatusActivity4 != null
            || x.fileFinishStatusActivity5 != null
            || x.fileFinishStatusActivity6 != null
            || x.fileFinishStatusActivity7 != null
            || x.fileFinishStatusActivity8 != null
            || x.fileFinishStatusActivity9 != null
            || x.fileFinishStatusActivity10 != null) && (x.finalFiles != null) && (x.workGroup.StartsWith(workGroup) || x.workGroup.Equals(workGroup))
            && (x.agreePublish == true)).ToList().ToPagedList(page ?? 1, 10);

                if (researchResult.TotalItemCount == 0)
                {
                    ViewBag.Nodata = "ไม่พบงานวิจัย";
                }

                return View(researchResult);
            }
            else
            {
                return View(researchResult);
            }
        }

        // GET: TreasuryWork
        public ActionResult InnovationTreasuryWork(int? page)
        {
            var innovation = db.Innovation;

            //--Pagination 10 each Select by Condition.
            var innovationResult = innovation.Where(x => x.workOverview == 100.00M && (x.fileFinishStatusActivity1 != null
            || x.fileFinishStatusActivity2 != null
            || x.fileFinishStatusActivity3 != null
            || x.fileFinishStatusActivity4 != null
            || x.fileFinishStatusActivity5 != null
            || x.fileFinishStatusActivity6 != null
            || x.fileFinishStatusActivity7 != null
            || x.fileFinishStatusActivity8 != null
            || x.fileFinishStatusActivity9 != null
            || x.fileFinishStatusActivity10 != null) && (x.finalFiles != null) && (x.agreePublish == true)).ToList().ToPagedList(page ?? 1, 10);

            if (innovationResult.TotalItemCount == 0)
            {
                ViewBag.Nodata = "ไม่พบงานนวัตกรรมที่เสร็จสิ้น";
            }

            return View(innovationResult);
        }

        [HttpPost]
        public ActionResult InnovationTreasuryWork(string budgetYear, string name, string creator, string workGroup, int? page)
        {
            var innovation = db.Innovation;

            //--Pagination 10 each Select by Condition.
            var innovationResult = innovation.Where(x => x.workOverview == 100.00M && (x.fileFinishStatusActivity1 != null
            || x.fileFinishStatusActivity2 != null
            || x.fileFinishStatusActivity3 != null
            || x.fileFinishStatusActivity4 != null
            || x.fileFinishStatusActivity5 != null
            || x.fileFinishStatusActivity6 != null
            || x.fileFinishStatusActivity7 != null
            || x.fileFinishStatusActivity8 != null
            || x.fileFinishStatusActivity9 != null
            || x.fileFinishStatusActivity10 != null) && (x.finalFiles != null) && (x.agreePublish == true)).ToList().ToPagedList(page ?? 1, 10);


            //--Search Engine
            if (budgetYear != "-- ปีงบประมาณ --")
            {
                innovationResult = db.Innovation.Where(x => x.workOverview == 100.00M && (x.fileFinishStatusActivity1 != null
            || x.fileFinishStatusActivity2 != null
            || x.fileFinishStatusActivity3 != null
            || x.fileFinishStatusActivity4 != null
            || x.fileFinishStatusActivity5 != null
            || x.fileFinishStatusActivity6 != null
            || x.fileFinishStatusActivity7 != null
            || x.fileFinishStatusActivity8 != null
            || x.fileFinishStatusActivity9 != null
            || x.fileFinishStatusActivity10 != null) && (x.finalFiles != null) && (x.budgetYear.StartsWith(budgetYear) || x.budgetYear.Equals(budgetYear))
            && (x.agreePublish == true)).ToList().ToPagedList(page ?? 1, 10);

                if (innovationResult.TotalItemCount == 0)
                {
                    ViewBag.Nodata = "ไม่พบงานนวัตกรรม";
                }

                return View(innovationResult);
            }
            if (name != "")
            {

E-RIMS/Views/TreasuryWork/AcademicTreasuryWork.cshtml
@using PagedList;
@using PagedList.Mvc;

@model IPagedList<E_RIMS.Models.Research>

@{
    ViewBag.Title = "คลังผลงานวิชาการ";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")">หน้าแรก</a></li>
        <li class="breadcrumb-item"><a href="@Url.Action("Index", "TreasuryWork")">คลังผลงาน</a></li>
        <li class="breadcrumb-item active" aria-current="page">@ViewBag.Title</li>
    </ol>
</nav>

<div class="card">
    <div class="card-header">
        <h3>งานวิชาการที่ดำเนินการแล้วเสร็จ</h3>
    </div>
    <div class="card-body">
        <h5 class="card-title"><i class="fa fa-book-medical"></i>&nbsp;@ViewBag.Title</h5>
        <hr />
        <div class="card">
            <div class="card-header">
                ค้นหางานวิชาการ
            </div>
            <div class="card-body">
                @using (Html.BeginForm("AcademicTreasuryWork", "TreasuryWork", FormMethod.Post))
                {
                    <div class="form-row">
                        <div class="form-group col-2">
                            <label class="" for="">ปีงบประมาณ</label>
                            <select class="custom-select custom-select-sm" id="" name="budgetYear">
                                <option selected>-- ปีงบประมาณ --</option>
                                <option>2559</option>
                                <option>2560</option>
                                <option>2561</option>
                                <option>2562</option>
                                <option>2563</option>
                                <option>2564</option>
                                <option>2565</option>
                                <option>2566</option>
                                <option>2567</option>
                                <option>2568</option>
                                <option>2569</option>
                                <option>2570</option>
                                <option>2571</option>
                                <option>2572</option>
                                <option>2573</option>
                                <option>2574</option>
                                <option>2575</option>
                                <option>2576</option>
                                <option>2577</option>
                                <option>2578</option>
                                <option>2579</option>
                                <option>2580</option>
                            </select>
                        </div>
                        <div class="form-group col-3">
                            <label class="" for="">ชื่องานวิชาการ</label>
                            <input type="text" class="form-control form-control-sm" name="name" />
                        </div>
                        <div class="form-group col-3">
                            <label class="" for="">นักวิจัย</label>
                            <input type="text" class="form-control form-control-sm" name="creator" />
                        </div>
                        <div class="form-group col-4">
                            <label class="">กลุ่มงาน</label>
                            <select class="form-control custom-select-sm" name="workGroup">
                                <option selected>-- กลุ่มงาน --</option>
                                <option>งานเภสัชกรรม</option>
                                <option>บริหารทั่วไป</option>
                                <option>พัฒนานวัตกรรมและวิจัย และงานควบคุมโรคเขตเมือง</option>
                                <option>พัฒนาระบบบริหารองค์กร และงานสถาปัตยกรรมข้อมูล</option>
                                <option>ยุทธศาสตร์ แผนงาน และเครือข่าย</option>
                                <option>ระบาดวิทยาและตอบโต้ภาวะฉุกเฉินทางด้านสาธารณสุข</option>
                                <option>โรคติดต่อ</option>
                                <option>โรคไม่ติดต่อ</option>
                                <option>ศูนย์ควบคุมโรคติดต่อนำโดยแมลงที่ 6.1 ศรีราชา</option>
                                <option>ศูนย์ควบคุมโรคติดต่อนำโดยแมลงที่ 6.2 สระแก้ว</option>
                                <option>ศูนย์ควบคุมโรคติดต่อนำโดยแมลงที่ 6.3 ระยอง</option>
                                <option>ศูนย์ควบคุมโรคติดต่อนำโดยแมลงที่ 6.4 ตราด</option>
                                <option>ศูนย์ควบคุมโรคติดต่อนำโดยแมลงที่ 6.5 จันทบุรี</option>
                                <option>สื่อสารความเสี่ยงโรคและภัยสุขภาพ</option>
                                <option>หน่วยกามโรคและโรคเอดส์ที่ 6.1 บางละมุง</option>
                                <option>ห้องปฏิบัติการทางการแพทย์ด้านควบคุมโรค</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group text-right">
                        <button type="submit" class="btn btn-info btn-sm"><i class="fa fa-search"></i>&nbsp;ค้นหางานวิชาการ</button>
                    </div>
                }
            </div>
        </div>
        <br />
        <h5 class="card-title">รายการงานวิชาการ</h5>
        <table class="table table-striped">
            <thead>
                <tr class="text-center">
                    <th scope="col">ปีงบประมาณ</th>
                    <th scope="col">ชื่องานวิชาการ</th>
                    <th scope="col">นักวิจัย</th>
                    <th scope="col">กลุ่มงาน</th>
                    <th scope="col">จำนวนผู้เข้าชม(ครั้ง)</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td class="text-center">@Html.DisplayFor(modelItem => item.budgetYear)</td>
                    <td><a href="@Url.Action("DetailResearch"+"/"+item.id,"Research")">@Html.DisplayFor(modelItem => item.name)</a></td>
                    <td>@Html.DisplayFor(modelItem => item.creator)</td>
                    <td>@Html.DisplayFor(modelItem => item.workGroup)</td>
                    <td class="text-center">@Html.DisplayFor(modelItem => item.views)</td>
                </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="6" class="text-center">
                        <div class="row">
                            <div class="col-6"></div>
                            <div class="col-6">
                                @Html.PagedListPager(Model, page => Url.Action("AcademicTreasuryWork", new { page }))
                            </div>
                        </div>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
</div>

E-RIMS/Views/TreasuryWork/Index.cshtml
@{
    ViewBag.Title = "คลังผลงาน";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")">หน้าแรก</a></li>
        <li class="breadcrumb-item active" aria-current="page">คลังผลงาน</li>
    </ol>
</nav>

<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-body text-center">
                <a href="@Url.Action("ResearchTreasuryWork","TreasuryWork")">
                    <img src="~/Image/researcher.png" style="height:250px; margin:10px;">
                    <h4 class="card-title">งานวิจัย</h4>
                </a>
            </div>
        </div>
    </div>

    <div class="col">
        <div class="card">
            <div class="card-body text-center">
                <a href="@Url.Action("AcademicTreasuryWork","TreasuryWork")">
                    <img src="~/Image/Books_PNG.png" style="height:250px; margin:10px;">
                    <h4 class="card-title">งานวิชาการ</h4>
                </a>
            </div>
        </div>
    </div>

    <div class="col">
        <div class="card">
            <div class="card-body text-center">
                <a href="@Url.Action("InnovationTreasuryWork","TreasuryWork")">
                    <img src="~/Image/innovator.png" style="height:250px; margin:10px;">
                    <h4 class="card-title">นวัตกรรม</h4>
                </a>
            </div>
        </div>
    </div>

</div>

E-RIMS/Views/TreasuryWork/InnovationTreasuryWork.cshtml
@model IPagedList<E_RIMS.Models.Innovation>
@using PagedList;
@using PagedList.Mvc;

@{
    ViewBag.Title = "คลังผลงานนวัตกรรม";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="@Url.Action("Index", "Home")">หน้าแรก</a></li>
        <li class="breadcrumb-item"><a href="@Url.Action("Index", "TreasuryWork")">คลังผลงาน</a></li>
        <li class="breadcrumb-item active" aria-current="page">@ViewBag.Title</li>
    </ol>
</nav>

<div class="card">
    <div class="card-header">
        <h3>คลังผลงานนวัตกรรมที่ดำเนินการแล้วเสร็จ&nbsp;</h3>
    </div>
    <div class="card-body">
        <h5 class="card-title"><i class="fa fa-book-medical"></i>&nbsp;@ViewBag.Title</h5>
        <hr />
        <div class="card">
            <div class="card-header">
                ค้นหางานนวัตกรรม
            </div>
            <div class="card-body">
                @using (Html.BeginForm("InnovationTreasuryWork", "TreasuryWork", FormMethod.Post))
                {
                    <div class="form-row">
                        <div class="form-group col-2">
                            <label class="" for="">ปีงบประมาณ</label>
                            <select class="custom-select custom-select-sm" id="" name="budgetYear">
                                <option selected>-- ปีงบประมาณ --</option>
                                <option>2559</option>
                                <option>2560</option>
                                <option>2561</option>
                                <option>2562</option>
                                <option>2563</option>
                                <option>2564</option>
                                <option>2565</option>
                                <option>2566</option>
                                <option>2567</option>
                                <option>2568</option>
                                <option>2569</option>
                                <option>2570</option>
                                <option>2571</option>
                                <option>2572</option>
                                <option>2573</option>
                                <option>2574</option>
                                <option>2575</option>
                                <option>2576</option>
                                <option>2577</option>
                                <option>2578</option>
                                <option>2579</option>
                                <option>2580</option>
                            </select>
                        </div>
                        <div class="form-group col-3">
                            <label class="" for="">ชื่อนวัตกรรม</label>
                            <input type="text" class="form-control form-control-sm" name="name" />
                        </div>
                        <div class="form-group col-3">
                            <label class="" for="">นวัตกร</label>
                            <input type="text" class="form-control form-control-sm" name="creator" />
                        </div>
                        <div class="form-group col-4">
                            <label class="">กลุ่มงาน</label>
                            <select class="form-control custom-select-sm" name="workGroup">
                                <option selected>-- กลุ่มงาน --</option>
                                <option>งานเภสัชกรรม</option>
                                <option>บริหารทั่วไป</option>
                                <option>พัฒนานวัตกรรมและวิจัย และงานควบคุมโรคเขตเมือง</option>
                                <option>พัฒนาระบบบริหารองค์กร และงานสถาปัตยกรรมข้อมูล</option>
                                <option>ยุทธศาสตร์ แผนงาน และเครือข่าย</option>
                                <option>ระบาดวิทยาและตอบโต้ภาวะฉุกเฉินทางด้านสาธารณสุข</option>
                                <option>โรคติดต่อ</option>
                                <option>โรคไม่ติดต่อ</option>
                                <option>ศูนย์ควบคุมโรคติดต่อนำโดยแมลงที่ 6.1 ศรีราชา</option>
                                <option>ศูนย์ควบคุมโรคติดต่อนำโดยแมลงที่ 6.2 สระแก้ว</option>
                                <option>ศูนย์ควบคุมโรคติดต่อนำโดยแมลงที่ 6.3 ระยอง</option>
                                <option>ศูนย์ควบคุมโรคติดต่อนำโดยแมลงที่ 6.4 ตราด</option>
                                <option>ศูนย์ควบคุมโรคติดต่อนำโดยแมลงที่ 6.5 จันทบุรี</option>
                                <option>สื่อสารความเสี่ยงโรคและภัยสุขภาพ</option>
                                <option>หน่วยกามโรคและโรคเอดส์ที่ 6.1 บางละมุง</option>
                                <option>ห้องปฏิบัติการทางการแพทย์ด้านควบคุมโรค</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group text-right">
                        <button type="submit" class="btn btn-info btn-sm"><i class="fa fa-search"></i>&nbsp;ค้นหานวัตกรรม</button>
                    </div>
                }
            </div>
        </div>
        <br />
        <h5 class="card-title">รายงานนวัตกรรม</h5>
        <table class="table table-striped">
            <thead>
                <tr class="text-center">
                    <th scope="col">#</th>
                    <th scope="col">ปีงบประมาณ</th>
                    <th scope="col">นวัตกรรม</th>
                    <th scope="col">ประเภท</th>
                    <th scope="col">นวัตกร</th>
                    <th scope="col">กลุ่มงาน</th>
                    <th scope="col">จำนวนผู้เข้าชม(ครั้ง)</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.date)</td>
                    <td class="text-center">@Html.DisplayFor(modelItem => item.budgetYear)</td>
                    <td><a href="@Url.Action("DetailInnovation"+"/"+item.id,"Innovation")">@Html.DisplayFor(modelItem => item.name)</a></td>
                    <td>@Html.DisplayFor(modelItem => item.type)</td>
                    <td>@Html.DisplayFor(modelItem => item.creator)</td>
                    <td>@Html.DisplayFor(modelItem => item.workGroup)</td>
                    <td class="text-center">@Html.DisplayFor(modelItem => item.views)</td>
                </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="6" class="text-center">
                        <div class="row">
                            <div class="col-6"></div>
                            <div class="col-6">
                                @Html.PagedListPager(Model, page => Url.Action("InnovationTreasuryWork", new { page }))
                            </div>
                        </div>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
</div>